### ISSUE TITLE
Data panel is blank

### ISSUE THREAD

**Issue by phamaralbr** [cryinkfly/Autodesk-Fusion-360-for-Linux#571]
**Describe the bug**
Data panel won't load in, it's blank.

**To Reproduce**
After updating Fusion, data panel is now missing.
Tried reinstalling using the script, panel is still missing.

**Expected behavior**
Data panel should appear.

**Screenshots**

<img width="1727" height="1439" alt="Image" src="https://github.com/user-attachments/assets/3f2e4790-a01a-4f78-91e7-3ff7ad287ca0" />

**Desktop (please complete the following information):**
- Latest Fusion 360 - 2603.1.15
- RX 6800 XT + Mesa 25.1.4
- Fedora 42
- Gnome 48
- Happens in DX11, DX9 and OpenGL

**Comment by arobert2** [comment]
I am having this same issue.

- Latest Fusion 360 - 2603.1.15
- RTX 5070 TI + Mesa 25.1.4
- Fedora 42
- KDE Plasma 6.4.3
- Happens in DX11, DX9, OpenGL. No DX10 option.

I logged the outputs from wine. I've tried using Glorious Eggroll as well but I couldn't get past the splash screen. 

This error would spam across the console whenever I opened the Data Panel and stop when I closed it.
```
err:   Failed to create shared resource: VK_KHR_EXTERNAL_MEMORY_WIN32 not supported
warn:  D3D11: Failed to write shared resource info for a texture
err:   D3D11DXGIKeyedMutex::AcquireSync: Not supported
```
Attached is the log file.

[winelogs.log](https://github.com/user-attachments/files/21482705/winelogs.log)

**Comment by arobert2** [comment]
Got it working from these instructions

https://help.autodesk.com/view/fusion360/ENU/?caas=caas/sfdcarticles/sfdcarticles/Data-Panel-is-showing-blank-space.html

The preferences I set is
General > Graphics Driver > DirectX 11
Compatibility & Troubleshooting > Qt Rendering Hardware Interface API > OpenGL

After restart I was able to see the panel information again.

**Comment by DevTheFool** [comment]
> Got it working from these instructions
> 
> https://help.autodesk.com/view/fusion360/ENU/?caas=caas/sfdcarticles/sfdcarticles/Data-Panel-is-showing-blank-space.html
> 
> The preferences I set is General > Graphics Driver > DirectX 11 Compatibility & Troubleshooting > Qt Rendering Hardware Interface API > OpenGL
> 
> After restart I was able to see the panel information again.

Linux Mint 22.1, AMD Ryzen 9 3900X and RTX 3060.
This worked for me, but I need it to put DirectX 9 in the `Graphics driver` and in the `Qt Rendering Hardware Interface API` OpenGL

**Comment by Zeroji** [comment]
Linux Mint 22.1, Ryzen 5 3600, RX 7800 XT here.
- DirectX 9 doesn't show data panel at all, the rest works
- DirectX 11 works fine but I get flicking like #504 (found a workaround)
- OpenGL Core Profile doesn't even update the center widget

My current settings are Graphics driver DirectX 11, and under "Compatibility & Troubleshooting" I've ended up with Qt Rendering API set to OpenGL and Chromium Graphics Backend set to Vulkan.

**Comment by phamaralbr** [comment]
Fixed my problems by switching to wine 9.22

https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/discussions/598#discussion-8992377

**Comment by duese22** [comment]
I still have the problem. Wine Version 10.0-20251023.
Additionally i also cannot open the settings.  So i cannot change the settings.

Edit: Give the settings some time. It will open after a few seconds.

**Comment by WilkoV** [comment]
Same here, new installation, CachyOS, Plasma, NVIDIA 1060

**Comment by duese22** [comment]
Ok, thanks everyone!
For me it works now. The Secret was to wait for the settings to appear. For me, with integrated AMD graphics. I got it to work only with DirectX 9 &  Chromium Graphics Backend set to Vulkan.

Again, thanks!
